---

title: "My awesome title"

date: 2019-01-09

---

author: Rev T
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just doing what the training wants me to. 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
